import createFetchClient from "openapi-fetch";
import type { paths } from "~/lib/api/schema"; // generated by openapi-typescript
import { baseUrl } from "~/utils/url";

export const $api = createFetchClient<paths>({
    baseUrl: `${baseUrl}/`,
});